---
title: "DDS_CaseStudy_2"
output:
  html_document:
    toc: true
    toc_depth: 2
author: "Kevin Boyd"
date: "11/21/2021"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Load Libraries
```{r, message=F}
library(tidyverse)
library(GGally)
library(cowplot)
library(class)
library(caret)
library(e1071)
library(reshape2)
library(stringr)
```


# Load and look at the data
```{r}
attrition.df <- read.csv("CaseStudy2-data.csv", header = T)
str(attrition.df)
```


# EDA
## Attrition Dependent on Marital Status
```{r}
# divorce contribute to attrition
bar <- ggplot(attrition.df, aes(x=MaritalStatus, fill = MaritalStatus)) +
  geom_bar() +
  facet_wrap(~Attrition) +
  ggtitle("Attrition Dependent on Marital Status ") +
  xlab("Attrition") +
  ylab("Count")
```


```{r}
# Yes Attrition
# make new data frames for married, divorced, and single
df1 <- attrition.df %>%
  filter(Attrition == "Yes")
df1length <- NROW(df1)
df1married <- length(grep("Married", df1$MaritalStatus))
df1divorced <- length(grep("Divorced", df1$MaritalStatus))
df1single <- length(grep("Single", df1$MaritalStatus))

Yes_df <- data.frame(MaritalStatus = c("Married","Divorced","Single"), 
                     Value = c(df1married,df1divorced,df1single))

plot1 <- ggplot(Yes_df, aes(x="", y=Value, fill=MaritalStatus)) +
  geom_bar(width = 1, stat = "identity") + xlab("") + ylab("") + ggtitle("Attrition: Yes")
pie1 <- plot1 + coord_polar("y", start=0)
```

```{r}
# No Attrition
# make new data frames for married, divorced, and single
df2 <- attrition.df %>%
  filter(Attrition == "No")
df2length <- NROW(df2)
df2married <- length(grep("Married", df2$MaritalStatus))
df2divorced <- length(grep("Divorced", df2$MaritalStatus))
df2single <- length(grep("Single", df2$MaritalStatus))

No_df <- data.frame(MaritalStatus = c("Married","Divorced","Single"), 
                     Value = c(df2married,df2divorced,df2single))

plot2 <- ggplot(No_df, aes(x="", y=Value, fill=MaritalStatus)) +
  geom_bar(width = 1, stat = "identity") + xlab("") + ylab("") + ggtitle("Attrition: No")
pie2 <- plot2 + coord_polar("y", start=0)
```

```{r}
piecharts <- plot_grid(pie2,pie1, ncol = 2,  labels = c("B","C"))
allplots <- plot_grid(bar,piecharts, nrow = 2, labels = "A")
allplots
```


## New part of the EDA
```{r, message=F}
ggpairs(attrition.df, columns = c(20,21,3))
```


## New EDA
```{r}
ggplot(attrition.df, aes(x=Attrition, y=JobSatisfaction)) +
  geom_jitter(height = 0.2, width = 0.20)
```

## New EDA
```{r}
ggplot(attrition.df, aes(x=MonthlyIncome, fill = Attrition)) +
  geom_histogram() +
  facet_wrap(~Attrition) +
  ggtitle("Monthly Income Based on Attrition") +
  xlab("Monthly Income") +
  ylab("Count")
```


## New EDA
```{r}
ggplot(attrition.df, aes(x=MonthlyIncome, fill = Attrition)) +
  geom_histogram() +
  facet_wrap(~JobRole) +
  ggtitle("Monthly Income Based on Job Role") +
  xlab("Monthly Income") +
  ylab("Count")
```

## New EDA
```{r}
ggplot(attrition.df, aes(x=PerformanceRating, fill = Attrition)) +
  geom_bar(position = "fill") +
  facet_wrap(~JobRole) +
  ggtitle("Performance Rating Based on Job Role") +
  xlab("Performance Rating") +
  ylab("Count") + 
  scale_y_continuous(labels = scales::percent)
```

## New EDA
```{r}
ggplot(attrition.df, aes(x=TotalWorkingYears, y=PercentSalaryHike, color = Attrition)) +
  geom_point() +
  ggtitle("Total Working Years vs Percent Salary Hike") +
  xlab("Total Working Years") +
  ylab("Percent Salary Hike") +
  facet_wrap(~JobRole)
```

# Models
```{r}
splitPerc <- .7
trainIndices <- sample(1:dim(attrition.df)[1],round(splitPerc * dim(attrition.df)[1]))
dfTrain <- attrition.df[trainIndices,]
dfTest <- attrition.df[-trainIndices,]
dfTrain <- na.omit(dfTrain)
dfTest <- na.omit(dfTest)

#knn model
classifications <- knn(dfTrain[,c(25,30)], dfTest[,c(25,30)], dfTrain$Attrition, 
                       prob = TRUE, k = 20)
table(dfTest$Attrition,classifications)
confusionMatrix(table(dfTest$Attrition,classifications))
```

# Loop for many k
```{r}
#Loop for many k and the average of many training / test partition
iterations = 100
numks = 50

masterAcc = matrix(nrow = iterations, ncol = numks)

for(j in 1:iterations)
{
  accs = data.frame(accuracy = numeric(100), k = numeric(100))
  trainIndices = sample(1:dim(attrition.df)[1],round(splitPerc * dim(attrition.df)[1]))
  train = attrition.df[trainIndices,]
  test = attrition.df[-trainIndices,]
  train = na.omit(train)
  test = na.omit(test)
  for(i in 1:numks)
  {
    classifications = knn(train[,c(25,30)],test[,c(25,30)],train$Attrition, prob = TRUE, k = i)
    table(classifications,test$Attrition)
    CM = confusionMatrix(table(classifications,test$Attrition))
    masterAcc[j,i] = CM$overall[1]
  }
  
}

MeanAcc = colMeans(masterAcc)

plot(seq(1,numks,1),MeanAcc, type = "l", xlab = "k", ylab = "Mean Accuracy", main = "Mean Accuracy of k Values")
```

# Internal k-NN Model
```{r}
classifications1 <- knn.cv(dfTrain[,c(2,20)],dfTrain$Attrition, k = 10)
confusionMatrix(table(classifications1,dfTrain$Attrition))
```


## New EDA
```{r}
ggplot(attrition.df, aes(x=Age, y=MonthlyIncome, color = Attrition)) +
  geom_point() +
  facet_wrap(~JobRole)
```


```{r}
sales.df <- attrition.df %>%
  filter(JobRole == "Research Scientist")

ggplot(sales.df, aes(x=Age, y=MonthlyIncome, color = Attrition)) +
  geom_point()

classifications2 <- knn.cv(sales.df[,c(2,20)],sales.df$Attrition, k = 15)
confusionMatrix(table(classifications2,sales.df$Attrition))
```



# Naive Bayes
```{r}
model <- naiveBayes(dfTrain[,c(24,20)],dfTrain$Attrition,laplace = 1)
table(predict(model,dfTest[,c(24,20)]),dfTest$Attrition)
confusionMatrix(table(predict(model,dfTest[,c(24,20)]),dfTest$Attrition))

model = naiveBayes(Attrition~.,data = dfTrain)
table(predict(model,dfTest))
confusionMatrix(table(predict(model,dfTest),dfTest$Attrition))
```

```{r}
sum(grepl("No", attrition.df$Attrition))
sum(grepl("Yes", dfTest$Attrition))
```


```{r}
set.seed(9)
new.df <- attrition.df[,c(2,3,4,5,6,7,15,16,18,20,29,30,32,33,34,35)]
splitPerc <- .7
trainIndices <- sample(1:dim(new.df)[1],round(splitPerc * dim(new.df)[1]))
dfTrain1 <- new.df[trainIndices,]
dfTest1 <- new.df[-trainIndices,]
dfTrain1 <- na.omit(dfTrain1)
dfTest1 <- na.omit(dfTest1)

model1 = naiveBayes(Attrition~.,data = dfTrain1)
confusionMatrix(table(predict(model1,dfTest1),dfTest1$Attrition))
```


# Linear Regression
```{r}
attrition.df$Attrition <- gsub("Yes", 1, attrition.df$Attrition)
attrition.df$Attrition <- gsub("No", 0, attrition.df$Attrition)
attrition.df$Attrition <- as.numeric(attrition.df$Attrition)
fit = lm(Attrition~Age*MonthlyIncome, data = attrition.df)
summary(fit)
confint(fit)
fit$coefficients
fit$residuals
sqrt(mean(fit$residuals^2))
sum((fit$residuals)^2)
sum((fit1$residuals)^2)
sum((fit2$residuals)^2)
```

```{r}
fit1 = lm(Attrition~Age+MonthlyIncome, data = attrition.df)
fit2 = lm(Attrition~MonthlyIncome, data = attrition.df)
hist(fit$residuals, col = "blue", main = "Histogram of Residuals")
summary(fit1)
summary(fit2)
```


# Train and Test for Linear Regression
```{r}
splitPerc <- .7
trainIndices <- sample(1:dim(attrition.df)[1],round(splitPerc * dim(attrition.df)[1]))
dfTrain <- attrition.df[trainIndices,]
dfTest <- attrition.df[-trainIndices,]
dfTrain <- na.omit(dfTrain)
dfTest <- na.omit(dfTest)

Model1_fit = lm(Attrition~Age*MonthlyIncome, data = dfTrain)
summary(Model1_fit)
Model1_Preds = predict(Model1_fit, newdata = dfTest)
as.data.frame(Model1_Preds)

MSPE = data.frame(Observed = dfTest$Attrition, Predicted = Model1_Preds)
MSPE$Resisdual = MSPE$Observed - MSPE$Predicted
MSPE$SquaredResidual = MSPE$Resisdual^2
MSPE
mean(MSPE$SquaredResidual)
RMSE <- mean((MSPE$Observed - MSPE$Predicted)^2) %>% sqrt()
RMSE
```

